### ISSUE TITLE
Send full user URL in the token response

### ISSUE THREAD

**Issue by aaronpk** [cweiske/anoweco#3]
Currently the response that includes the access token always returns `https://commentpara.de/` as the `me` URL, rather than the unique user URL that is generated for anonymous users. This means anyone logging in to e.g. Quill will end up logged in as the same user.

**Comment by cweiske** [comment]
Hm. You already get the new `me` when doing the auth code verification. And still quill uses the original `me` instead of the one it got from auth code verification response.

**Comment by cweiske** [comment]
"old me back" is fixed. I throw an error now if the wrong "me" is sent to the token endpoint.

**Comment by cweiske** [comment]
Discussion about that: https://chat.indieweb.org/dev/2017-08-18#t1503089497099000

**Comment by cweiske** [comment]
https://indieweb.org/File:micropub-auth-flow.png suggests step 3 is never executed. Discussion with @aaronpk suggests that the token endpoint should ignore the `me` parameter at all and return the `me` associated with the code.
